name: "Code Scanning - DevSkim"

on:
  push:
    paths:
    - '**'
  schedule:
    - cron: '0 3 * * 3'

jobs:
  DevSkim-Run:

    strategy:
      fail-fast: false

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    
    - name: DevSkim
      uses: microsoft/DevSkim-Action@v1
      with:
        # The sub directory of the repository root to scan. Repository root used by default.
        # Optionally scan the contents of archives.
        should-scan-archives: false
        # The filename for the output.
        output-filename: devskim-results.sarif
    
    - name: Upload Sarif
      uses: github/codeql-action/upload-sarif@v1
      with:
        sarif-file: devskim-results.sarif
