name: "Code Scanning - DevSkim (VS Code)"

on:
  push:
    branches:
    - main
    paths:
    - '**'
  schedule:
    - cron: '0 3 * * 3'

jobs:
  DevSkim-Run:

    strategy:
      fail-fast: false

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    
    - name: DevSkim
      uses: microsoft/DevSkim-Action@v1
      with:
        directory-to-scan: DevSkim-VSCode-Plugin
        should-scan-archives: false
        output-filename: devskim-results-vscode.sarif

    - name: Upload Sarif
      uses: github/codeql-action/upload-sarif@v1
      with:
        sarif_file: devskim-results-vscode.sarif

    - name: Archive artifacts
      uses: actions/upload-artifact@v2
      with:
        name: devskim-results-vscode.sarif
        path: |
          devskim-results-vscode.sarif